### ISSUE TITLE
Blank page on tiddly.alhur.es

### ISSUE THREAD

**Issue by acailly** [fiatjaf/tiddlywiki-remotestorage#5]
Few days ago I went on the site and everything was OK.
Today I only see a blank page 😢 

Can we install the plugin by another way?

**Comment by fiatjaf** [comment]
What? This is the oddest bug I've ever seen.

It's blank here also, but I didn't change anything, and if you press Ctrl+U you'll see the TiddlyWiki HTML all there.

Oh, wait, it's not all there, it's only partially there. The server is struggling somehow to send the entire file. Bizarre.

I can only fix this in the weekend, in the meantime download and run the default TiddlyWiki HTML file from https://raw.githubusercontent.com/fiatjaf/tiddlywiki-remotestorage-server/deploy/index.html and import the plugin from it.

**Comment by fiatjaf** [comment]
That is fixed now. Sorry for not knowing how to operate servers.

**Comment by acailly** [comment]
Thank you 🙂
